=== JoaoLobarinhas/DAW2019/Teste/pr.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT  project-record (header,workTeam,abstract,deliverables,footer)>
<!ELEMENT header (keyname,title,subtitle?,begin-date,end-date,supervisor)>
<!ELEMENT keyname (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT subtitle (#PCDATA)>
<!ELEMENT begin-date (#PCDATA)>
<!ELEMENT end-date (#PCDATA)>
<!ELEMENT supervisor (#PCDATA)>
<!ATTLIST supervisor url CDATA #IMPLIED>

<!ELEMENT workTeam (element+) >
<!ELEMENT element (number,name,email)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ATTLIST email url CDATA #REQUIRED>

<!ELEMENT abstract (#PCDATA | bold | italic | underline | link)*>
<!ELEMENT bold (#PCDATA | italic | underline | link)*>
<!ELEMENT italic (#PCDATA | bold | underline | link)*>
<!ELEMENT underline (#PCDATA | bold | italic | link)*>
<!ELEMENT link (#PCDATA | bold | italic | underline)*>
<!ATTLIST link url CDATA #REQUIRED>

<!ELEMENT deliverables (deliverable)+>
<!ELEMENT deliverable (#PCDATA)>
<!ATTLIST deliverable url CDATA #IMPLIED>

<!ELEMENT footer (#PCDATA) >

=== JoaoLobarinhas/DAW2019/trab6/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project-record SYSTEM "C:\Users\Lobarinhas\Desktop\UM\DesvolvimentoWebApp\DWeb2019\trab6\pr.dtd">
<project-record>
    <header>
        <keyname>TP5-DWeb2019</keyname>
        <title>TPC6: Aplicação Web de gestão do Arquivo Sonoro de Ernesto Veiga de Oliveira</title>
        <subtitle></subtitle>
        <begin-date>06/11/2019</begin-date>
        <end-date>07/11/2019</end-date>
        <supervisor url="http://www4.di.uminho.pt/~jcr">
            José Carlos Ramalho
        </supervisor>
    </header>
    <workTeam>
        <element>
            <number>PG41845</number>
            <name>João Lobarinhas Fernandes Miranda</name>
            <email url="pg41845@alunos.uminho.pt">pg41845@alunos.uminho.pt</email>
        </element>
    </workTeam>
    <abstract>
        <text>
            Converter o ficheiro "arq-son-EVO.xml" para o formato json.
        </text>
        <text>
            Criar uma aplicação web com todas as operações do CRUD
        </text>
    </abstract>
    <deliverables>
        <deliverable url="pr.xml">
            Ficheiro XML do Porject Record.
        </deliverable>
        <deliverable url="pr.dtd">
            DTD do Project Record.
        </deliverable>
        <deliverable url="arqson">
            Pasta onde guarda os ficheiros referentes a este tpc.
        </deliverable>
        <deliverable url="arqson/server.js">
            Ficheiro javascript que permite iniciar o servidor.
        </deliverable>
    </deliverables>
    <footer>
        07/11/2019
    </footer>
</project-record>

=== JoaoLobarinhas/DAW2019/trab5/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project-record SYSTEM "C:\Users\Lobarinhas\Desktop\UM\DesvolvimentoWebApp\DWeb2019\trab5\pr.dtd">
<project-record>
    <header>
        <keyname>TP5-DWeb2019</keyname>
        <title>TPC5: Servidor de Gestão de Tarefas</title>
        <subtitle></subtitle>
        <begin-date>30/10/2019</begin-date>
        <end-date>30/10/2019</end-date>
        <supervisor url="http://www4.di.uminho.pt/~jcr">
            José Carlos Ramalho
        </supervisor>
    </header>
    <workTeam>
        <element>
            <number>PG41845</number>
            <name>João Lobarinhas Fernandes Miranda</name>
            <email url="pg41845@alunos.uminho.pt">pg41845@alunos.uminho.pt</email>
        </element>
    </workTeam>
    <abstract>
        <text>
            Criar um servidor que permita fazer a gestão de tarefas
        </text>
        <text>
            Listar as tarefas existentes.
        </text>
        <text>
           Poder criar tarefas
        </text>
    </abstract>
    <deliverables>
        <deliverable url="pr.xml">
            Ficheiro XML do Porject Record.
        </deliverable>
        <deliverable url="pr.dtd">
            DTD do Project Record.
        </deliverable>
        <deliverable url="trab">
            Pasta onde guarda os ficheiros referentes a este tpc.
        </deliverable>
        <deliverable url="trab/server.js">
            Ficheiro javascript que permite iniciar o servidor.
        </deliverable>
        <deliverable url="trab/tarefas.json">
            Ficheiro json que permie armazenar as tarefas.
        </deliverable>
        <deliverable url="trab/layout.pug">
            Ficheiro que define o layout para a página web.
        </deliverable>
        <deliverable url="trab/index.pug">
            Ficheiro que permite criar dinamicamente a página web.
        </deliverable>
        <deliverable url="trab/erro.pug">
            Ficheiro que é criar uma página web em caso de erro.
        </deliverable>
        <deliverable url="trab/css">
            Pasta que armazena o css das páginas web.
        </deliverable>
    </deliverables>
    <footer>
        28/10/2019
    </footer>
</project-record>

=== JoaoLobarinhas/DAW2019/trab2/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project-record SYSTEM "C:\Users\Lobarinhas\Desktop\UM\DesvolvimentoWebApp\DWeb2019\trab2\pr.dtd">
<project-record>
    <header>
        <keyname>TP2-DWeb2019</keyname>
        <title>TPC2: DTDs e um pouco de XPath</title>
        <begin-date>15/10/2019</begin-date>
        <end-date>15/10/2019</end-date>
        <supervisor url="http://www4.di.uminho.pt/~jcr">
            José Carlos Ramalho
        </supervisor>
    </header>
    <workTeam>
        <element>
            <number>PG41845</number>
            <name>João Lobarinhas Fernandes Miranda</name>
            <email url="pg41845@alunos.uminho.pt">pg41845@alunos.uminho.pt</email>
        </element>
    </workTeam>
    <abstract>
        Neste trabalho prático consistio na resolução de 3 execicios, uma análise a <italic>project record</italic>
        e a especificação de um DTD para a sua estrutura, e a resolução o execício 6 e 7 da ficha 3.
    </abstract>
    <deliverables>
        <deliverable url="pr.xml">
            Ficheiro XML de acordo com o DTD criado.
        </deliverable>
        <deliverable url="pr.dtd">
            DTD criado de acordo com o project record.
        </deliverable>
        <deliverable url="exe6.txt">
            Respostas ao exercicio 6 da ficha 3.
        </deliverable>
        <deliverable url="arq.dtd">
            Dtd gerado do xml dos arqueossítios.
        </deliverable>
    </deliverables>
    <footer>
        15/10/2019
    </footer>
</project-record>

=== JoaoLobarinhas/DAW2019/trab8/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project-record SYSTEM "C:\Users\Lobarinhas\Desktop\UM\DesvolvimentoWebApp\DWeb2019\trab8\pr.dtd">
<project-record>
    <header>
        <keyname>TP8-DWeb2019</keyname>
        <title>TPC8: Exercício Nº 1: Prémios Nobel</title>
        <subtitle></subtitle>
        <begin-date>13/11/2019</begin-date>
        <end-date>13/11/2019</end-date>
        <supervisor url="http://www4.di.uminho.pt/~jcr">
            José Carlos Ramalho
        </supervisor>
    </header>
    <workTeam>
        <element>
            <number>PG41845</number>
            <name>João Lobarinhas Fernandes Miranda</name>
            <email url="pg41845@alunos.uminho.pt">pg41845@alunos.uminho.pt</email>
        </element>
    </workTeam>
    <abstract>
        <text>
            Converter o dataset disponibilizado nos recursos para um formato à tua escolha, ou usá-lo como está (há vários conversores online de XML para JSON e outros formatos), e colocá-lo no sistema que usarás para assegurar a sua persistência: ficheiro, MongoDB, json-server, etc; 
        </text>
        <text>
            Criar um servidor nodejs que dê suporte à um API de Dados
        </text>
    </abstract>
    <deliverables>
        <deliverable url="pr.xml">
            Ficheiro XML do Porject Record.
        </deliverable>
        <deliverable url="pr.dtd">
            DTD do Project Record.
        </deliverable>
        <deliverable url="nobel">
            Pasta onde guarda os ficheiros referentes a este tpc.
        </deliverable>
        <deliverable url="prize.json">
            Ficheiro json a ser importado para a base de dados MongoDB.
        </deliverable>
        <deliverable url="nobel/server.js">
            Ficheiro javascript que permite iniciar o servidor.
        </deliverable>
        <deliverable url="nobel/controllers/nobel.js">
            Ficheiro javascript que funciona como controlador do modelo.
        </deliverable>
        <deliverable url="nobel/model/nobel.js">
            Ficheiro javascript que foi criado com base na estrutura de dados já existe na base de dados, para que
            funcione como modelo.
        </deliverable>
        <deliverable url="nobel/routes/api.js">
            Ficheiro javascript que funciona trata dos pedidos recebidos por parte do cliente.
        </deliverable>
    </deliverables>
    <footer>
        10/11/2019
    </footer>
</project-record>

=== JoaoLobarinhas/DAW2019/trab4/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project-record SYSTEM "C:\Users\Lobarinhas\Desktop\UM\DesvolvimentoWebApp\DWeb2019\trab4\pr.dtd">
<project-record>
    <header>
        <keyname>TP4-DWeb2019</keyname>
        <title>TPC4: Servidor de ficheiros</title>
        <subtitle></subtitle>
        <begin-date>25/10/2019</begin-date>
        <end-date>28/10/2019</end-date>
        <supervisor url="http://www4.di.uminho.pt/~jcr">
            José Carlos Ramalho
        </supervisor>
    </header>
    <workTeam>
        <element>
            <number>PG41845</number>
            <name>João Lobarinhas Fernandes Miranda</name>
            <email url="pg41845@alunos.uminho.pt">pg41845@alunos.uminho.pt</email>
        </element>
    </workTeam>
    <abstract>
        <text>
            Descarregar o ficheiro com o dataset dos arqueossítios em XML: http://www4.di.uminho.pt/~jcr/XML/didac/xmldocs/arq.xml;
        </text>
        <text>
            Criar uma stylesheet XSLT que processe este ficheiro e gere um ficheiro por cada arqueossítio e os coloque numa pasta: arq1.xsml, arq2.xml, ...
        </text>
        <text>
            No passo anterior, cada ficheiro XML deverá estar associado a uma stylesheet XSLT que o transforma para HTML (deixei ajuda no material da aula4);
        </text>
        <text>
            Criar um servidor em nodejs que sirva os ficheiros, ou seja, responde aos pedidos: 
                localhost:7777/3  --> Coloca no browser o conteúdo do arq3.xml em formato HTML
                , localhost:7777/122  --> Coloca no browser o conteúdo do arq122.xml em formato HTML, e por aí adiante...
        </text>
        <text>
            Se conseguirem criem uma página de entrada com um índice que liga às outras páginas com pedidos...
        </text>
        <text>
            Há umas ratoeiras pelo caminho mas na aula tive o cuidado de criar exemplos de como "auscultar" situações problemáticas e resolvê-las...
        </text>
    </abstract>
    <deliverables>
        <deliverable url="pr.xml">
            Ficheiro XML do Porject Record.
        </deliverable>
        <deliverable url="pr.dtd">
            DTD do Project Record.
        </deliverable>
        <deliverable url="trab">
            Pasta onde guarda os ficheiros referentes a este tpc.
        </deliverable>
        <deliverable url="trab/arq.xsl">
            XSL que define o estilo da página HTML.
        </deliverable>
        <deliverable url="trab/arq.xml">
            XML dos Arqueossítios.
        </deliverable>
        <deliverable url="trab/arq.dtd">
            DTD dos Arqueossítios.
        </deliverable>
        <deliverable url="trab/arq-create.xsl">
            Gera os XML dos Arqueossítios com o estilo definido pelo arq.xsl.
        </deliverable>
        <deliverable url="arq/server.js">
            Servidor em node.js que permite fazer a gestão das páginas.
        </deliverable>
        <deliverable url="arq/xmls">
            Pasta com os XML's gerados.
        </deliverable>
    </deliverables>
    <footer>
        28/10/2019
    </footer>
</project-record>

=== JoaoLobarinhas/DAW2019/Teste/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project-record SYSTEM "C:\Users\Lobarinhas\Desktop\UM\DesvolvimentoWebApp\DWeb2019\Teste\pr.dtd">
<project-record>
    <header>
        <keyname>Ficha daw2020-e1</keyname>
        <title>Avaliação: Desenvolvimento de Aplicações Web</title>
        <subtitle></subtitle>
        <begin-date>16/01/2020</begin-date>
        <end-date>16/01/2020</end-date>
        <supervisor url="http://www4.di.uminho.pt/~jcr">
            José Carlos Ramalho
        </supervisor>
    </header>
    <workTeam>
        <element>
            <number>PG41845</number>
            <name>João Lobarinhas Fernandes Miranda</name>
            <email url="pg41845@alunos.uminho.pt">pg41845@alunos.uminho.pt</email>
        </element>
    </workTeam>
    <abstract>
        <text>
            Exercício Nº 1: Arquivo de Música Digital
        </text>
        <text>
            Exercício Nº 2: CLAV: Classificação e Avaliação da Informação Pública
        </text>
    </abstract>
    <deliverables>
        <deliverable url="pr.xml">
            Ficheiro XML do Porject Record.
        </deliverable>
        <deliverable url="pr.dtd">
            DTD do Project Record.
        </deliverable>
        <deliverable url="Arquivo de Música Digital">
            Pasta onde guarda os ficheiros referentes ao 1 exercício.
        </deliverable>
        <deliverable url="Arquivo de Música Digital/arquivoMusical.json">
            Ficheiro json a ser importado para a base de dados MongoDB.
        </deliverable>
        <deliverable url="CLAV">
            Pasta onde guarda os ficheiros referentes ao 2 exercício.
        </deliverable>
    </deliverables>
    <footer>
        16/01/2020
    </footer>
</project-record>

=== JoaoLobarinhas/DAW2019/trab3/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project-record SYSTEM "C:\Users\Lobarinhas\Desktop\UM\DesvolvimentoWebApp\DWeb2019\trab2\pr.dtd">
<project-record>
    <header>
        <keyname>TP3-DWeb2019</keyname>
        <title>TPC3: Transformações com XSLT</title>
        <subtitle></subtitle>
        <begin-date>16/10/2019</begin-date>
        <end-date>16/10/2019</end-date>
        <supervisor url="http://www4.di.uminho.pt/~jcr">
            José Carlos Ramalho
        </supervisor>
    </header>
    <workTeam>
        <element>
            <number>PG41845</number>
            <name>João Lobarinhas Fernandes Miranda</name>
            <email url="pg41845@alunos.uminho.pt">pg41845@alunos.uminho.pt</email>
        </element>
    </workTeam>
    <abstract>
        <text>
            Especificação de uma <italic>stylesheet</italic> para transformar o <bold>PR.xml em PR.html</bold>;
        </text>
        <text>
            Especificação de uma <italic>stylesheet</italic> para gerar um <italic>website</italic> para os arqueossítios.
        </text>
    </abstract>
    <deliverables>
        <deliverable url="pr.xml">
            Ficheiro XML do Porject Record.
        </deliverable>
        <deliverable url="pr.dtd">
            DTD do Project Record.
        </deliverable>
        <deliverable url="pr.html">
            Html do Project Record.
        </deliverable>
        <deliverable url="pr.xsl">
            XSL do Project Record.
        </deliverable>
        <deliverable url="arq/arq.xml">
            XML dos Arqueossítios.
        </deliverable>
        <deliverable url="arq/arq.dtd">
            DTD dos Arqueossítios.
        </deliverable>
        <deliverable url="arq/arq.xsl">
            XSL dos Arqueossítios.
        </deliverable>
        <deliverable url="arq/html">
            Páginas Html geradas do XSL dos Arqueossítios.
        </deliverable>
    </deliverables>
    <footer>
        15/10/2019
    </footer>
</project-record>

=== JoaoLobarinhas/DAW2019/trab7/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project-record SYSTEM "C:\Users\Lobarinhas\Desktop\UM\DesvolvimentoWebApp\DWeb2019\trab6\pr.dtd">
<project-record>
    <header>
        <keyname>TP7-DWeb2019</keyname>
        <title>TPC7: Aplicação Web de gestão de Filmes</title>
        <subtitle></subtitle>
        <begin-date>07/11/2019</begin-date>
        <end-date>10/11/2019</end-date>
        <supervisor url="http://www4.di.uminho.pt/~jcr">
            José Carlos Ramalho
        </supervisor>
    </header>
    <workTeam>
        <element>
            <number>PG41845</number>
            <name>João Lobarinhas Fernandes Miranda</name>
            <email url="pg41845@alunos.uminho.pt">pg41845@alunos.uminho.pt</email>
        </element>
    </workTeam>
    <abstract>
        <text>
            Responder a algumas perguntas referentes a queries feita utilizando MongoDB  
        </text>
        <text>
            Importar o documento <bold>"movies.json"</bold> para uma base de dados <bold>MongoDB</bold>
        </text>
        <text>
            Implementar uma aplicação web que consiga fazer todas as funcionalidades do CRUD.
        </text>
    </abstract>
    <deliverables>
        <deliverable url="pr.xml">
            Ficheiro XML do Porject Record.
        </deliverable>
        <deliverable url="pr.dtd">
            DTD do Project Record.
        </deliverable>
        <deliverable url="perguntasMongo.txt">
            Respostas as perguntas propostas.
        </deliverable>
        <deliverable url="movies">
            Pasta onde guarda os ficheiros referentes a este tpc.
        </deliverable>
        <deliverable url="movies.json">
            Ficheiro json a ser importado para a base de dados MongoDB.
        </deliverable>
        <deliverable url="movies/server.js">
            Ficheiro javascript que permite iniciar o servidor.
        </deliverable>
        <deliverable url="movies/controllers/movies.js">
            Ficheiro javascript que funciona como controlador do modelo.
        </deliverable>
        <deliverable url="movies/model/movie.js">
            Ficheiro javascript que foi criado com base na estrutura de dados já existe na base de dados, para que
            funcione como modelo.
        </deliverable>
        <deliverable url="movies/routes/api.js">
            Ficheiro javascript que funciona como middleware entre o cliente e a base de dados.
        </deliverable>
    </deliverables>
    <footer>
        10/11/2019
    </footer>
</project-record>
